server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-uri:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/product?serverTimezone=UTC
    username: coupang
    password: coupang
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true


resilience4j.circuitbreaker:
  instances:
    review:
      registerHealthIndicator: true
      minimumNumberOfCalls: 10
      slowCallDurationThreshold: 10000
      slowCallRateThreshold: 50
